### ISSUE TITLE
Problem running blhelisuite to communicate with ESCs

### ISSUE THREAD

**Issue by dustin** [lkaino/Triflight#1]
I have the mini tri and electronics kit.  I found that the default config does not support oneshot, so I wanted to update it via the latest blhelisuite.

I'm not experienced with blheli in particular, but know what needs to be done and had a vague idea of how to get there.  I plugged in my FC and opened up blhelisuite, told it I had an AVR with cleanflight as the interface.  On "check" the motors will beep in sequence and I'll get a report that there are no ESCs.

If I try to read config from a specific ESC, it will beep it forever asking me to power cycle.  Power cycling doesn't help.  It just wakes up and keeps beeping.  This is the closest to a sign of progress I've got.

Discussion in #cleanflight points to a possible workaround:

> 00:30 ducktaperules well if you have a linker tool, you can go into cleanflgiht CLI use the "1wire 1" comand, disconect in the configurator, then touch your linker tool on top of the esc contacts for esc 1 and connect to it in blheli. update / change settings. then when your done power cycle the fc
> 00:30 ducktaperules rinse and repeat for each esc using "1wire 2" and "1wire 3"
> 00:40 Simon-- that just tristates the pwm output pin?
> 00:40 Simon-- I could also just finish the abandoned usblinker branch :)
> 00:42 Simon-- or merge the other crap over softserial, which is probably better, since it _should_ be tiny..
> 01:00 ducktaperules either option would be great
> 01:01 ducktaperules and yeah it just tristates the output pin, but thtas enough to reprogram if you need to
> 01:02 ducktaperules even a dedicated hex that you could flash to, update esc then flash back, without wiping eprom would be good

It seems the bl20s may have a simonk bootloader.  In any case, stuff doesn't seem to work well (for me at least).

**Comment by DKDarkness** [comment]
Current RCExplorer ESCs: DYS SN20A ESC (BLHeli) have a SimonK (SN) bootloader and BLHeli firmware. Currently Cleanflight (thus Triflight) can not communicate with the SimonK bootloader through the flight controller. To communicate with the ESCs through the flight controller, re-flash your ESCs with the BLHeli bootloader (bootloader and firmware are two different things). You will need a special tool (Atmel Atmega Socket Firmware Flashing Tool and USBasp AVR Programming Device for ATMEL proccessors) to do so. Read more: http://blog.oscarliang.net/change-bootloader-esc-atmel/
