### ISSUE TITLE
The VERY_FAST_MATH should be removed.

### ISSUE THREAD

**Issue by Bengt-M** [lkaino/Triflight#10]
The unit tests fail. Its a tiny error but probably accumulative (not random noise). Thousand times every second and it may add up.
The original committer @DigitalEntity, who I think introduced the fast math, had it commented it out originally. Then something happened in a BF detour. In current CF it is commented out again.
See math.h, line 26, or use attached patch which also updates the names to current CF.
/B
[Math.patch.txt](https://github.com/lkaino/Triflight/files/97883/Math.patch.txt)

**Comment by lkaino** [comment]
Thanks, will do.

**Comment by lkaino** [comment]
This will be removed in the Cleanflight merge.
