### ISSUE TITLE
Servo stucked after connecting battery

### ISSUE THREAD

**Issue by Nullstr1ng** [lkaino/Triflight#12]
I am using the 0.5 version of Triflight on my CC3D. By the way, I checkedout the version 0.5 tag and used this command make TARGET=CC3D

So after flashing, cycled the power and connected the battery, the servo was stuck, tilted left (if the tricopter is facing at you) I don't understand why but in betaflight, it's working perfectly.

Can someone take a look at this?

Servo is connected at M4 by the way so I assume this is correct.

**Comment by lkaino** [comment]
Unfortunately I don't have a CC3D target to test on. I have already a branch where I have merged to latest Cleanflight. Need to do a bit of testing on that one before releasing a hex for testing. That might fix the CC3D issues also.

If you feel adventurous you could try to build a hex from that branch and test out carefully.

**Comment by Nullstr1ng** [comment]
Thanks! I would really like to try TriFlight. Thanks for having a time developing a firmware for our tricopters

**Comment by Nullstr1ng** [comment]
servo_pwm_rate didnt help either..

**Comment by lkaino** [comment]
Could you test on beta 2?
