### ISSUE TITLE
Sparky Target in RC5 broken

### ISSUE THREAD

**Issue by Ga1j1n** [lkaino/Triflight#15]
The Sparky hex corrupts the board prompting an unrecognised target message in windows devices, the bootloader bins must be shorted to allow re-flashing of cleanflight.

(It's a shame as I was looking forward to trying it)

**Comment by lkaino** [comment]
Too bad I don't have a sparky board to test on :(.

**Comment by Ga1j1n** [comment]
I'm happy to test, or could make a donation towards one, I have to admit I'm gravitating towards the Sparky2 and raceflight these days for Quads but my Trifecta Tri is built with a Sparky 1.

http://www.ebay.co.uk/itm/CC3D-Upgrade-FC-Sparky-Flight-Controller-V2-Tau-Labs-10DOF-with-Protect-Case-/271917877268?hash=item3f4f918814:g:2NkAAOSwu4BVk2Kk

http://www.xt-xinte.com/F16821.html

**Comment by lkaino** [comment]
Could try to make a build without the servo feedback pins configured. It's
most likely that or then sparky has less flash/ram. Could also make another
build without GPS for testing.
29.3.2016 7.48 ip. "Ga1j1n" notifications@github.com kirjoitti:

**Comment by Ga1j1n** [comment]
Sounds good, let me know and I'll flash it.

Thanks
