### ISSUE TITLE
GPS Navigation Merge with Triflight?

### ISSUE THREAD

**Issue by JuliettPapa** [lkaino/Triflight#2]
HI,

Since the inav code will soon be getting merged with cleanflight, will it be possible to have these advantages with triflight, too?

**Comment by lkaino** [comment]
Hello,

Yes it's possible once it's merged to Cleanflight. There might be
difficulties to get it fit to memory of naze32 with the tricopter stuff.

**Comment by JuliettPapa** [comment]
Thnx for the good news ;-))
Memory problems with naze are already discussed I think. Maybe CLI gets removed. I hope Triflight & Inav will fit, then.

**Comment by lkaino** [comment]
Cleanflight is now merged, just need to wait for the iNav merge to Cleanflight.
