### ISSUE TITLE
GPS settings are unavailable in 0.4 version of triflight

### ISSUE THREAD

**Issue by Ultratkinfo** [lkaino/Triflight#4]
When configuring gps, the following options are unavailable in CLI: gps_provider, gps_auto_config and so on. Also, in cleanflight, GPS options (in Configuration tab) do not persist.

**Comment by Bengt-M** [comment]
The GPS fetaure was removed in 476597ca5dc16927e0a3519b0518019d2a0d7dd9 when GTUNE was added .

Based on [this post](http://rcexplorer.se/forums/topic/triflight-setup-guide/page/8/#post-25884) I'd guess the trade-off should be different today. Or maybe that whas a confusion with autotune.

Pls try to enable again.
Before checking other gps issues, obviously :)

If something has to go, to save space, we may need forum opinions for the best compromise.

**Comment by wolfpackt99** [comment]
also trying to save gps. maybe i need new firmware. settings in cli are gone. running .4

**Comment by lkaino** [comment]
0.5 beta 2 should have working gps

**Comment by wolfpackt99** [comment]
Great news. Thanks.
