### ISSUE TITLE
SERVO_TILT not working on F3 target.

### ISSUE THREAD

**Issue by LLac** [lkaino/Triflight#45]
Activating servo_tilt no longer working on F3 board. Works fine on naze32. Which outputs are the servo pins on the F3FC (besides the tail servo)? On the naze32 it was the first 2 output pins.

**Comment by lkaino** [comment]
There is only one servo output in RCEXPLORERF3 board. The PWM3 or PPM could be used for secondary output trhough the resource CLI command.
